name: ingest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.7.4.post0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.1
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - cdsapi=0.5.1
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - google-api-core=1.31.1
  - google-auth=1.34.0
  - google-cloud-core=1.7.2
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.2
  - googleapis-common-protos=1.53.0
  - grpcio=1.38.1
  - idna=3.1
  - importlib-metadata=3.10.1
  - ipykernel=6.0.3
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - ld_impl_linux-64=2.36.1
  - libcrc32c=1.1.1
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgomp=11.1.0
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=11.1.0
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - multidict=5.1.0
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandoc=2.14.1
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.1
  - pyu2f=0.1.5
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.26.0
  - rsa=4.7.2
  - send2trash=1.7.1
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.10.1
  - testpath=0.5.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.62.0
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
