name: validate
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3.2
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=9.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.10.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - bokeh=3.1.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cartopy=0.20.2
  - certifi=2024.8.30
  - cf_xarray=0.7.2
  - cffi=1.15.0
  - cftime=1.6.4
  - charset-normalizer=2.0.12
  - click=8.1.7
  - cloudpickle=3.1.0
  - comm=0.2.1
  - contourpy=1.1.1
  - cryptography=37.0.1
  - curl=7.83.1
  - cycler=0.11.0
  - cytoolz=0.12.3
  - dask=2023.5.0
  - dask-core=2023.5.0
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.5.0
  - entrypoints=0.4
  - esmf=8.3.1
  - esmpy=8.3.1
  - executing=0.8.3
  - expat=2.4.8
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.12.1
  - frozenlist=1.3.0
  - fsspec=2024.10.0
  - geos=3.10.3
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - glog=0.6.0
  - google-api-core=2.8.1
  - google-auth=2.8.0
  - google-cloud-core=2.3.1
  - google-cloud-storage=2.4.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.2
  - grpc-cpp=1.46.3
  - grpcio=1.46.3
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - h5netcdf=1.1.0
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=69.1
  - idna=3.3
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=5.7.1
  - ipykernel=6.14.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.6.0
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.3
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libabseil=20211102.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcrc32c=1.1.2
  - libcurl=7.83.1
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libgoogle-cloud=1.40.2
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm10=10.0.0
  - libllvm13=13.0.1
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=14.3
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzip=1.9.2
  - libzlib=1.3.1
  - llvmlite=0.41.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mpi=1.0
  - mpi4py=3.1.3
  - mpich=4.0.3
  - msgpack-python=1.0.8
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclassic=0.3.7
  - nbclient=0.6.4
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf-fortran=4.6.0
  - netcdf4=1.6.2
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numba=0.58.1
  - numpy=1.22.4
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - orc=1.7.5
  - packaging=21.3
  - pandas=1.4.2
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parallelio=2.5.9
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - proj=9.0.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - protobuf=3.20.1
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=9.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.3.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pyshp=2.3.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.8
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=23.1.0
  - qt=5.12.9
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.0
  - rsa=4.8
  - s2n=1.0.10
  - scipy=1.8.1
  - send2trash=1.8.0
  - setuptools=62.3.4
  - shapely=1.8.2
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sparse=0.13.0
  - sqlite=3.40.0
  - stack_data=0.3.0
  - tbb=2021.7.0
  - tblib=3.0.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toolz=1.0.0
  - tornado=6.1
  - traitlets=5.2.2.post1
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - widgetsnbextension=4.0.13
  - xarray=2022.3.0
  - xesmf=0.8.8
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.8.0
  - zlib=1.3.1
  - zstd=1.5.2
