name: analyze
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20220623.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - aws-c-auth=0.6.23
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.9
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.18
  - aws-c-http=0.7.3
  - aws-c-io=0.13.14
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.3
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.57
  - babel=2.10.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - blosc=1.21.5
  - bokeh=3.1.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - certifi=2024.8.30
  - cffi=1.15.0
  - cftime=1.6.4
  - charset-normalizer=2.0.12
  - click=8.1.7
  - cloudpickle=3.1.0
  - colorama=0.4.4
  - comm=0.2.1
  - contourpy=1.1.1
  - cryptography=38.0.4
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2023.5.0
  - dask-core=2023.5.0
  - dbus=1.13.18
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.5.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.6.4
  - flit-core=3.7.1
  - fontconfig=2.14.2
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozenlist=1.3.0
  - fsspec=2024.10.0
  - gflags=2.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.6.0
  - google-api-core=2.22.0
  - google-auth=2.35.0
  - google-cloud-core=2.3.1
  - google-cloud-storage=2.4.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.2
  - grpc-cpp=1.51.1
  - grpcio=1.51.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5netcdf=1.1.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.3
  - importlib-metadata=8.5.0
  - importlib-resources=5.7.1
  - importlib_metadata=8.5.0
  - importlib_resources=5.7.1
  - ipykernel=6.14.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.6.0
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.3
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.9.1
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libgomp=14.2.0
  - libgoogle-cloud=2.5.0
  - libgrpc=1.51.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.43
  - libpq=12.20
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=12.1.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - msgpack-python=1.0.8
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql=5.7.20
  - nbclassic=0.3.7
  - nbclient=0.6.4
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.6.5
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - numpy=1.22.4
  - openjpeg=2.5.0
  - openssl=3.4.0
  - orc=1.8.2
  - packaging=21.3
  - pandas=1.4.2
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.1
  - pcre2=10.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=22.1.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - proto-plus=1.25.0
  - protobuf=4.21.12
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.8
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=23.1.0
  - qt-main=5.15.2
  - re2=2022.06.01
  - readline=8.2
  - requests=2.28.0
  - rsa=4.8
  - s2n=1.3.35
  - send2trash=1.8.0
  - setuptools=62.3.4
  - sip=6.5.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sqlite=3.42.0
  - stack_data=0.3.0
  - tblib=3.0.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.2.2.post1
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - ucx=1.13.1
  - unicodedata2=15.1.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - widgetsnbextension=4.0.13
  - xarray=2022.3.0
  - xkeyboard-config=2.43
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.6
