name: ingest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - ld_impl_linux-64=2.36.1
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgomp=11.1.0
  - libstdcxx-ng=11.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.2.2
  - python=3.8.10
  - python_abi=3.8
  - readline=8.1
  - setuptools=49.6.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
