name: visualize
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.7.4.post0
  - alsa-lib=1.2.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bokeh=2.3.3
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - cairo=1.16.0
  - cartopy=0.19.0.post1
  - certifi=2021.5.30
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.5.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - curl=7.78.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.7.2
  - dask-core=2021.7.2
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.0.9
  - distributed=2021.7.2
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2021.7.0
  - gdal=3.2.1
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - google-api-core=1.31.1
  - google-auth=1.34.0
  - google-cloud-core=1.7.2
  - google-cloud-storage=1.41.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.3
  - googleapis-common-protos=1.53.0
  - grpcio=1.38.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - hdf4=4.2.15
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=68.1
  - idna=3.1
  - ipykernel=6.0.3
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json-c=0.15
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcrc32c=1.1.1
  - libcurl=7.78.0
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgdal=3.2.1
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libglib=2.68.3
  - libgomp=11.1.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.17
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.17.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.2
  - netcdf4=1.5.6
  - nspr=4.30
  - nss=3.67
  - numpy=1.21.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.3.1
  - parso=0.8.2
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.2.2
  - pixman=0.40.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=7.2.0
  - prompt-toolkit=3.0.19
  - protobuf=3.17.2
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=22.1.0
  - qt=5.12.9
  - readline=8.1
  - requests=2.26.0
  - rsa=4.7.2
  - scipy=1.7.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - tblib=1.7.0
  - tiledb=2.2.9
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzcode=2021a
  - tzdata=2021a
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zeromq=4.3.4
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
