name: visualize
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4.post0
  - appnope=0.1.2
  - async-timeout=3.0.1
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bokeh=2.3.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - cartopy=0.19.0.post1
  - certifi=2021.5.30
  - cffi=1.14.6
  - cftime=1.5.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - curl=7.78.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.7.2
  - dask-core=2021.7.2
  - debugpy=1.4.1
  - decorator=5.0.9
  - distributed=2021.7.2
  - freetype=2.10.4
  - fsspec=2021.7.0
  - geos=3.9.1
  - google-api-core=1.31.1
  - google-auth=1.34.0
  - google-cloud-core=1.7.2
  - google-cloud-storage=1.41.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.3
  - googleapis-common-protos=1.53.0
  - grpcio=1.38.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - heapdict=1.0.1
  - idna=3.1
  - ipykernel=6.0.3
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libcurl=7.78.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libzip=1.8.0
  - llvm-openmp=12.0.1
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - ncurses=6.2
  - netcdf4=1.5.7
  - numpy=1.21.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.3.1
  - parso=0.8.2
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - proj=7.2.0
  - prompt-toolkit=3.0.19
  - protobuf=3.17.2
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.26.0
  - rsa=4.7.2
  - scipy=1.7.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - tblib=1.7.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xarray=0.19.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zeromq=4.3.4
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.5.0
