name: deliver
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - aiohttp=3.7.4.post0
  - anyio=3.3.0
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.1
  - bokeh=2.3.3
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2021.5.30
  - cf_xarray=0.6.0
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.5.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - curl=7.78.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.7.2
  - dask-core=2021.7.2
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - distributed=2021.7.2
  - entrypoints=0.3
  - esmf=8.1.1
  - esmpy=8.1.1
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2021.7.0
  - gdal=3.3.1
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - google-api-core=1.31.1
  - google-auth=1.34.0
  - google-cloud-core=1.7.2
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.2
  - googleapis-common-protos=1.53.0
  - grpcio=1.38.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.6.3
  - importlib_metadata=4.6.3
  - ipykernel=6.0.3
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.10.2
  - jupyterlab=3.1.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.1
  - jupyterlab_widgets=1.0.0
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libcurl=7.78.0
  - libcxx=12.0.1
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgdal=3.3.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.68.3
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.17.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzip=1.8.0
  - llvm-openmp=12.0.1
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.4.2
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - nb_conda_kernels=2.3.1
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf-fortran=4.5.3
  - netcdf4=1.5.7
  - notebook=6.4.0
  - numpy=1.21.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.3.1
  - pandoc=2.14.1
  - pandocfilters=1.4.2
  - parso=0.8.2
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=8.0.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - protobuf=3.17.2
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=22.1.0
  - rasterio=1.2.6
  - readline=8.1
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - rsa=4.7.2
  - scipy=1.7.0
  - send2trash=1.7.1
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.16.0
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - tblib=1.7.0
  - terminado=0.10.1
  - testpath=0.5.0
  - tiledb=2.3.2
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzcode=2021a
  - tzdata=2021a
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xesmf=0.6.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
