name: analyze
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - backcall=0.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.1.1
  - cryptography=43.0.0
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - google-api-core=2.22.0
  - google-auth=2.35.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.18.2
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.65.0
  - grpcio=1.62.2
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcxx=19.1.3
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.62.2
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.47.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.3
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - multidict=6.0.5
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.0.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - proto-plus=1.25.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytz=2024.2
  - pyu2f=0.1.5
  - pyzmq=26.2.0
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - setuptools=75.3.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.45.0
  - widgetsnbextension=4.0.13
  - xarray=2022.11.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
