name: validate
channels:
  - conda-forge
dependencies:
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=21.4.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - cartopy=0.20.2
  - certifi=2021.10.8
  - cf_xarray=0.7.0
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cryptography=36.0.2
  - curl=7.82.0
  - cycler=0.11.0
  - esmf=8.2.0
  - esmpy=8.2.0
  - fonttools=4.31.2
  - freetype=2.10.4
  - frozenlist=1.3.0
  - geos=3.10.2
  - giflib=5.2.1
  - google-api-core=2.5.0
  - google-auth=2.6.2
  - google-cloud-core=2.2.2
  - google-cloud-storage=2.1.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.56.0
  - grpcio=1.45.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - jbig=2.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.82.0
  - libcxx=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.20.0
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mpi=1.0
  - mpi4py=3.1.3
  - mpich=4.0.1
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf-fortran=4.5.4
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - pillow=9.0.1
  - pip=22.0.4
  - proj=9.0.0
  - protobuf=3.20.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyproj=3.3.0
  - pyshp=2.2.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - pyu2f=0.1.5
  - readline=8.1
  - requests=2.27.1
  - rsa=4.8
  - scipy=1.8.0
  - setuptools=61.2.0
  - shapely=1.8.0
  - six=1.16.0
  - sparse=0.3.1
  - sqlite=3.37.1
  - tk=8.6.12
  - tornado=6.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wheel=0.37.1
  - xarray=2022.3.0
  - xesmf=0.6.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.2
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
