name: validate
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.0
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.1
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.4
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blosc=1.21.6
  - bokeh=3.1.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cartopy=0.21.1
  - certifi=2024.8.30
  - cf_xarray=0.8.4
  - cffi=1.17.0
  - cftime=1.6.4
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - contourpy=1.1.1
  - cryptography=43.0.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask-core=2023.5.0
  - distributed=2023.5.0
  - esmf=8.6.1
  - esmpy=8.6.1
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.10.0
  - geos=3.11.2
  - gflags=2.2.2
  - glog=0.7.1
  - google-api-core=1.31.5
  - google-auth=1.35.0
  - google-cloud-core=1.6.0
  - google-cloud-storage=2.2.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.65.0
  - h2=4.1.0
  - h5netcdf=1.1.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - jinja2=3.1.4
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.3
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libopenblas=0.3.25
  - libpng=1.6.44
  - libprotobuf=3.21.12
  - libre2-11=2024.07.02
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libthrift=0.21.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=19.1.3
  - llvmlite=0.41.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf-fortran=4.6.1
  - netcdf4=1.7.1
  - numba=0.58.1
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.4.0
  - packaging=24.2
  - pandas=1.5.3
  - partd=1.4.1
  - pillow=10.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - pooch=1.8.2
  - proj=9.2.0
  - protobuf=4.21.12
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pyopenssl=24.2.1
  - pyparsing=3.1.4
  - pyproj=3.5.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python_abi=3.8
  - pytz=2024.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - scipy=1.10.1
  - setuptools=75.3.0
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sparse=0.15.4
  - sqlite=3.47.0
  - tblib=3.0.0
  - tk=8.6.13
  - toolz=1.0.0
  - tornado=6.4.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.45.0
  - xarray=2023.1.0
  - xesmf=0.8.8
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
